/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Badge from './Badge';
import Group from './Group';
import VcContext from './VcContext';
import VcInfo from './VcInfo';
import VcSchema from './VcSchema';
import VcSchemaProperty from './VcSchemaProperty';

/**
 * The AllOfFileVcSchema model module.
 * @module model/AllOfFileVcSchema
 * @version 0.9.2
 */
export default class AllOfFileVcSchema extends VcSchema {
  /**
   * Constructs a new <code>AllOfFileVcSchema</code>.
   * (任意) ファイルに紐づいたVCスキーマ
   * @alias module:model/AllOfFileVcSchema
   * @class
   * @extends module:model/VcSchema
   * @param id {} (必須) VCスキーマの識別子
   * @param title {} (必須) VCスキーマのタイトル
   * @param version {} (必須) VCスキーマのバージョン
   * @param description {} (任意) VCスキーマの説明文
   * @param createdBy {} (必須) VCスキーマを作成したユーザーアカウント。
   * @param createdAt {} (必須) VCスキーマの作成日時
   * @param updatedAt {} (必須) VCスキーマの更新日時
   */
  constructor(id, title, version, description, createdBy, createdAt, updatedAt) {
    super(id, title, version, description, createdBy, createdAt, updatedAt);
  }

  /**
   * Constructs a <code>AllOfFileVcSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfFileVcSchema} obj Optional instance to populate.
   * @return {module:model/AllOfFileVcSchema} The populated <code>AllOfFileVcSchema</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfFileVcSchema();
      VcSchema.constructFromObject(data, obj);
    }
    return obj;
  }
}
