/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Badge from './Badge';

/**
 * The AllOfVcInfoBadge model module.
 * @module model/AllOfVcInfoBadge
 * @version 0.9.2
 */
export default class AllOfVcInfoBadge extends Badge {
  /**
   * Constructs a new <code>AllOfVcInfoBadge</code>.
   * (任意) VC情報と紐付いたバッジ
   * @alias module:model/AllOfVcInfoBadge
   * @class
   * @extends module:model/Badge
   * @param id {} (必須) バッジの識別子
   * @param description {} (任意) バッジの作成目的や用途など任意で設定可能な説明文
   * @param status {} (必須) バッジの状態(1: アクティブ, 0: 停止中)
   * @param createdAt {} (必須) グループの作成日時
   * @param updatedAt {} (必須) グループの最終更新日時
   */
  constructor(id, description, status, createdAt, updatedAt) {
    super(id, description, status, createdAt, updatedAt);
  }

  /**
   * Constructs a <code>AllOfVcInfoBadge</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfVcInfoBadge} obj Optional instance to populate.
   * @return {module:model/AllOfVcInfoBadge} The populated <code>AllOfVcInfoBadge</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfVcInfoBadge();
      Badge.constructFromObject(data, obj);
    }
    return obj;
  }
}
