/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Group from './Group';

/**
 * The AllOfVcSchemaResponseDtoFile model module.
 * @module model/AllOfVcSchemaResponseDtoFile
 * @version 0.9.2
 */
export default class AllOfVcSchemaResponseDtoFile extends File {
  /**
   * Constructs a new <code>AllOfVcSchemaResponseDtoFile</code>.
   * VCスキーマに紐付けるバッジ用の画像。&#x60;isBadgeSchema&#x60;プロパティが&#x60;true&#x60;の場合必須。
   * @alias module:model/AllOfVcSchemaResponseDtoFile
   * @class
   * @extends module:model/File
   * @param id {} (必須) ファイルの識別子
   * @param filename {} (任意) システム内で管理される際にシステムによって名付けられるユニークなファイル名
   * @param originalname {} (必須) システムへアップロード時の元のファイル名
   * @param type {} (必須) ファイル形式
   * @param fileData {} (必須) ファイルのバイナリデータ
   * @param executed {} (任意) ファイルがCSVの場合、アカウントデータ生成実行に使用されたか。(true: 実行済み, false: 未使用)
   * @param status {} (必須) ファイルのステータス
   * @param group {} (任意) ファイルを紐づけたグループの配列
   * @param createdBy {} (必須) ファイルをアップロードしたユーザーアカウント。
   * @param createdAt {} (必須) ファイルの作成日時
   * @param updatedAt {} (必須) グループの最終更新日時
   */
  constructor(id, filename, originalname, type, fileData, executed, status, group, createdBy, createdAt, updatedAt) {
    super(id, filename, originalname, type, fileData, executed, status, group, createdBy, createdAt, updatedAt);
  }

  /**
   * Constructs a <code>AllOfVcSchemaResponseDtoFile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllOfVcSchemaResponseDtoFile} obj Optional instance to populate.
   * @return {module:model/AllOfVcSchemaResponseDtoFile} The populated <code>AllOfVcSchemaResponseDtoFile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllOfVcSchemaResponseDtoFile();
      File.constructFromObject(data, obj);
    }
    return obj;
  }
}
