/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ConnectVcSchemasDto model module.
 * @module model/ConnectVcSchemasDto
 * @version 0.9.2
 */
export default class ConnectVcSchemasDto {
  /**
   * Constructs a new <code>ConnectVcSchemasDto</code>.
   * @alias module:model/ConnectVcSchemasDto
   * @class
   * @param vcSchemaIds {Array.<String>} (必須) グループに紐付けを行うVCスキーマ識別子の配列
   */
  constructor(vcSchemaIds) {
    this.vcSchemaIds = vcSchemaIds;
  }

  /**
   * Constructs a <code>ConnectVcSchemasDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConnectVcSchemasDto} obj Optional instance to populate.
   * @return {module:model/ConnectVcSchemasDto} The populated <code>ConnectVcSchemasDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ConnectVcSchemasDto();
      if (data.hasOwnProperty('vcSchemaIds'))
        obj.vcSchemaIds = ApiClient.convertToType(data['vcSchemaIds'], ['String']);
    }
    return obj;
  }
}

/**
 * (必須) グループに紐付けを行うVCスキーマ識別子の配列
 * @member {Array.<String>} vcSchemaIds
 */
ConnectVcSchemasDto.prototype.vcSchemaIds = undefined;

