/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GenerateDidDto model module.
 * @module model/GenerateDidDto
 * @version 0.9.2
 */
export default class GenerateDidDto {
  /**
   * Constructs a new <code>GenerateDidDto</code>.
   * @alias module:model/GenerateDidDto
   * @class
   * @param didMethod {Array.<module:model/GenerateDidDto.DidMethodEnum>} (必須) 新規生成するDIDのメソッド。(現在対応するDIDメソッド: \"key\", \"ether\", \"ethr:sepolia\", \"ethr:arbitrum:goerli\", \"web\")
   */
  constructor(didMethod) {
    this.didMethod = didMethod;
  }

  /**
   * Constructs a <code>GenerateDidDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GenerateDidDto} obj Optional instance to populate.
   * @return {module:model/GenerateDidDto} The populated <code>GenerateDidDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GenerateDidDto();
      if (data.hasOwnProperty('didMethod'))
        obj.didMethod = ApiClient.convertToType(data['didMethod'], ['String']);
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('domainName'))
        obj.domainName = ApiClient.convertToType(data['domainName'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>didMethod</code> property.
 * @enum {String}
 * @readonly
 */
GenerateDidDto.DidMethodEnum = {
  /**
   * value: "key"
   * @const
   */
  key: "key",

  /**
   * value: "web"
   * @const
   */
  web: "web",

  /**
   * value: "ethr:sepolia"
   * @const
   */
  ethrsepolia: "ethr:sepolia",

  /**
   * value: "ethr"
   * @const
   */
  ethr: "ethr",

  /**
   * value: "ethr:arbitrum:goerli"
   * @const
   */
  ethrarbitrumgoerli: "ethr:arbitrum:goerli"
};
/**
 * (必須) 新規生成するDIDのメソッド。(現在対応するDIDメソッド: \"key\", \"ether\", \"ethr:sepolia\", \"ethr:arbitrum:goerli\", \"web\")
 * @member {Array.<module:model/GenerateDidDto.DidMethodEnum>} didMethod
 */
GenerateDidDto.prototype.didMethod = undefined;

/**
 * (任意) DIDの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: did-for-project1)
 * @member {String} label
 */
GenerateDidDto.prototype.label = undefined;

/**
 * (任意) did:webメソッドでDIDを生成する際に必要なドメイン名。DIDによって指定されたドメインがドメインネームシステム(DNS)を通じて解決されるときのホスト名。did:webメソッド以外では必要のないパラメータなため任意の項目である。
 * @member {String} domainName
 */
GenerateDidDto.prototype.domainName = undefined;

/**
 * (任意) DIDの生成目的や用途など任意で設定可能な説明文。
 * @member {String} description
 */
GenerateDidDto.prototype.description = undefined;

