/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UpdateVcSchemaDto model module.
 * @module model/UpdateVcSchemaDto
 * @version 0.9.2
 */
export default class UpdateVcSchemaDto {
  /**
   * Constructs a new <code>UpdateVcSchemaDto</code>.
   * @alias module:model/UpdateVcSchemaDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateVcSchemaDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateVcSchemaDto} obj Optional instance to populate.
   * @return {module:model/UpdateVcSchemaDto} The populated <code>UpdateVcSchemaDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateVcSchemaDto();
      if (data.hasOwnProperty('groupIds'))
        obj.groupIds = ApiClient.convertToType(data['groupIds'], ['String']);
      if (data.hasOwnProperty('contexts'))
        obj.contexts = ApiClient.convertToType(data['contexts'], ['String']);
    }
    return obj;
  }
}

/**
 * (必須) VCスキーマを紐づけるグループ識別子の配列。
 * @member {Array.<String>} groupIds
 */
UpdateVcSchemaDto.prototype.groupIds = undefined;

/**
 * (必須) VCスキーマを紐づけるcontext項目の配列。
 * @member {Array.<String>} contexts
 */
UpdateVcSchemaDto.prototype.contexts = undefined;

