/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UploadVCDto model module.
 * @module model/UploadVCDto
 * @version 0.9.2
 */
export default class UploadVCDto {
  /**
   * Constructs a new <code>UploadVCDto</code>.
   * @alias module:model/UploadVCDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UploadVCDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UploadVCDto} obj Optional instance to populate.
   * @return {module:model/UploadVCDto} The populated <code>UploadVCDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UploadVCDto();
      if (data.hasOwnProperty('credentialObject'))
        obj.credentialObject = ApiClient.convertToType(data['credentialObject'], Object);
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * (任意) JSON形式のVCオブジェクト。ファイルアップロードではなくテキストを用いて作成する場合のみ必須
 * @member {Object} credentialObject
 */
UploadVCDto.prototype.credentialObject = undefined;

/**
 * (任意) VCの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: vc-for-project1)
 * @member {String} label
 */
UploadVCDto.prototype.label = undefined;

/**
 * (任意) VCの発行目的や用途など任意で設定可能な説明文。
 * @member {String} description
 */
UploadVCDto.prototype.description = undefined;

