/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The VcContext model module.
 * @module model/VcContext
 * @version 0.9.2
 */
export default class VcContext {
  /**
   * Constructs a new <code>VcContext</code>.
   * @alias module:model/VcContext
   * @class
   * @param id {String} (必須) VCスキーマの識別子
   * @param context {String} (必須) VCスキーマのタイトル
   * @param vcSchema {Object} (任意) contextが紐づくVCスキーマ
   * @param createdAt {String} (必須) VCスキーマの作成日時
   * @param updatedAt {String} (必須) VCスキーマの更新日時
   */
  constructor(id, context, vcSchema, createdAt, updatedAt) {
    this.id = id;
    this.context = context;
    this.vcSchema = vcSchema;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Constructs a <code>VcContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VcContext} obj Optional instance to populate.
   * @return {module:model/VcContext} The populated <code>VcContext</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VcContext();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('context'))
        obj.context = ApiClient.convertToType(data['context'], 'String');
      if (data.hasOwnProperty('vcSchema'))
        obj.vcSchema = ApiClient.convertToType(data['vcSchema'], Object);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'String');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'String');
    }
    return obj;
  }
}

/**
 * (必須) VCスキーマの識別子
 * @member {String} id
 */
VcContext.prototype.id = undefined;

/**
 * (必須) VCスキーマのタイトル
 * @member {String} context
 */
VcContext.prototype.context = undefined;

/**
 * (任意) contextが紐づくVCスキーマ
 * @member {Object} vcSchema
 */
VcContext.prototype.vcSchema = undefined;

/**
 * (必須) VCスキーマの作成日時
 * @member {String} createdAt
 */
VcContext.prototype.createdAt = undefined;

/**
 * (必須) VCスキーマの更新日時
 * @member {String} updatedAt
 */
VcContext.prototype.updatedAt = undefined;

