/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The VerifyBadgeDto model module.
 * @module model/VerifyBadgeDto
 * @version 0.9.2
 */
export default class VerifyBadgeDto {
  /**
   * Constructs a new <code>VerifyBadgeDto</code>.
   * @alias module:model/VerifyBadgeDto
   * @class
   * @param vpInfoId {String} (任意) 
   */
  constructor(vpInfoId) {
    this.vpInfoId = vpInfoId;
  }

  /**
   * Constructs a <code>VerifyBadgeDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerifyBadgeDto} obj Optional instance to populate.
   * @return {module:model/VerifyBadgeDto} The populated <code>VerifyBadgeDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerifyBadgeDto();
      if (data.hasOwnProperty('veriifyVC'))
        obj.veriifyVC = ApiClient.convertToType(data['veriifyVC'], 'Boolean');
      if (data.hasOwnProperty('vpInfoId'))
        obj.vpInfoId = ApiClient.convertToType(data['vpInfoId'], 'String');
    }
    return obj;
  }
}

/**
 * (任意) バッジに紐づいたVC情報を検証するか否か。`true`の場合VC情報をfalseの場合`vpInfoId`で指定されたVP情報を検証する
 * @member {Boolean} veriifyVC
 * @default true
 */
VerifyBadgeDto.prototype.veriifyVC = true;

/**
 * (任意) 
 * @member {String} vpInfoId
 * @default 'false'
 */
VerifyBadgeDto.prototype.vpInfoId = 'false';

