/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Verification from './Verification';

/**
 * The VerificationsResponseDto model module.
 * @module model/VerificationsResponseDto
 * @version 0.9.2
 */
export default class VerificationsResponseDto {
  /**
   * Constructs a new <code>VerificationsResponseDto</code>.
   * @alias module:model/VerificationsResponseDto
   * @class
   * @param items {Array.<module:model/Verification>} 
   * @param meta {Object} 
   * @param links {Object} 
   */
  constructor(items, meta, links) {
    this.items = items;
    this.meta = meta;
    this.links = links;
  }

  /**
   * Constructs a <code>VerificationsResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerificationsResponseDto} obj Optional instance to populate.
   * @return {module:model/VerificationsResponseDto} The populated <code>VerificationsResponseDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerificationsResponseDto();
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [Verification]);
      if (data.hasOwnProperty('meta'))
        obj.meta = ApiClient.convertToType(data['meta'], Object);
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], Object);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Verification>} items
 */
VerificationsResponseDto.prototype.items = undefined;

/**
 * @member {Object} meta
 */
VerificationsResponseDto.prototype.meta = undefined;

/**
 * @member {Object} links
 */
VerificationsResponseDto.prototype.links = undefined;

