/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The VerificationResponseDto model module.
 * @module model/VerificationResponseDto
 * @version 0.9.2
 */
export default class VerificationResponseDto {
  /**
   * Constructs a new <code>VerificationResponseDto</code>.
   * @alias module:model/VerificationResponseDto
   * @class
   * @param id {String} 検証結果の識別子
   * @param label {String} 検証結果の識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: verify-for-check)
   * @param result {Boolean} (必須) VC/VPの検証結果(true: 検証に成功, false: 検証に失敗)
   * @param createdBy {Object} グループを作成したユーザーアカウント
   * @param vcInfo {Object} 検証を実行したVC情報の識別子
   * @param vpInfo {Object} 検証を実行したVP情報の識別子
   * @param createdAt {String} 検証実行時の日時
   * @param updatedAt {String} 検証結果の最終更新日
   */
  constructor(id, label, result, createdBy, vcInfo, vpInfo, createdAt, updatedAt) {
    this.id = id;
    this.label = label;
    this.result = result;
    this.createdBy = createdBy;
    this.vcInfo = vcInfo;
    this.vpInfo = vpInfo;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Constructs a <code>VerificationResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerificationResponseDto} obj Optional instance to populate.
   * @return {module:model/VerificationResponseDto} The populated <code>VerificationResponseDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerificationResponseDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = ApiClient.convertToType(data['result'], 'Boolean');
      if (data.hasOwnProperty('createdBy'))
        obj.createdBy = ApiClient.convertToType(data['createdBy'], Object);
      if (data.hasOwnProperty('vcInfo'))
        obj.vcInfo = ApiClient.convertToType(data['vcInfo'], Object);
      if (data.hasOwnProperty('vpInfo'))
        obj.vpInfo = ApiClient.convertToType(data['vpInfo'], Object);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'String');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'String');
    }
    return obj;
  }
}

/**
 * 検証結果の識別子
 * @member {String} id
 */
VerificationResponseDto.prototype.id = undefined;

/**
 * 検証結果の識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: verify-for-check)
 * @member {String} label
 */
VerificationResponseDto.prototype.label = undefined;

/**
 * (必須) VC/VPの検証結果(true: 検証に成功, false: 検証に失敗)
 * @member {Boolean} result
 */
VerificationResponseDto.prototype.result = undefined;

/**
 * グループを作成したユーザーアカウント
 * @member {Object} createdBy
 */
VerificationResponseDto.prototype.createdBy = undefined;

/**
 * 検証を実行したVC情報の識別子
 * @member {Object} vcInfo
 */
VerificationResponseDto.prototype.vcInfo = undefined;

/**
 * 検証を実行したVP情報の識別子
 * @member {Object} vpInfo
 */
VerificationResponseDto.prototype.vpInfo = undefined;

/**
 * 検証実行時の日時
 * @member {String} createdAt
 */
VerificationResponseDto.prototype.createdAt = undefined;

/**
 * 検証結果の最終更新日
 * @member {String} updatedAt
 */
VerificationResponseDto.prototype.updatedAt = undefined;

