/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The VerificationDto model module.
 * @module model/VerificationDto
 * @version 0.9.2
 */
export default class VerificationDto {
  /**
   * Constructs a new <code>VerificationDto</code>.
   * @alias module:model/VerificationDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>VerificationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerificationDto} obj Optional instance to populate.
   * @return {module:model/VerificationDto} The populated <code>VerificationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerificationDto();
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('vcInfoId'))
        obj.vcInfoId = ApiClient.convertToType(data['vcInfoId'], 'String');
      if (data.hasOwnProperty('vpInfoId'))
        obj.vpInfoId = ApiClient.convertToType(data['vpInfoId'], 'String');
      if (data.hasOwnProperty('vcObject'))
        obj.vcObject = ApiClient.convertToType(data['vcObject'], Object);
      if (data.hasOwnProperty('vpObject'))
        obj.vpObject = ApiClient.convertToType(data['vpObject'], Object);
    }
    return obj;
  }
}

/**
 * (必須) 検証結果の識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: verify-for-check)
 * @member {String} label
 */
VerificationDto.prototype.label = undefined;

/**
 * (任意) 検証を実行するVC情報の識別子。VC情報の識別子を指定して検証を実行する場合は必須。
 * @member {String} vcInfoId
 */
VerificationDto.prototype.vcInfoId = undefined;

/**
 * (任意) 検証を実行するVP情報の識別子。VP情報の識別子を指定して検証を実行する場合は必須。
 * @member {String} vpInfoId
 */
VerificationDto.prototype.vpInfoId = undefined;

/**
 * (任意) 検証を実行するVCのJSONテキストデータ。VCのJSONテキストデータを入力して検証を実行する場合は必須。
 * @member {Object} vcObject
 */
VerificationDto.prototype.vcObject = undefined;

/**
 * (任意) 検証を実行するVPのJSONテキストデータ。VPのJSONテキストデータを入力して検証を実行する場合は必須。
 * @member {Object} vpObject
 */
VerificationDto.prototype.vpObject = undefined;

