/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import AddLabelToVpInfoDto from '../model/AddLabelToVpInfoDto';
import CreateVpInfoDto from '../model/CreateVpInfoDto';
import UpdateVcInfoDto from '../model/UpdateVcInfoDto';
import VpInfoDetailDto from '../model/VpInfoDetailDto';
import VpInfoResponseDto from '../model/VpInfoResponseDto';

/**
* VpInfos service.
* @module api/VpInfosApi
* @version 0.9.2
*/
export default class VpInfosApi {

    /**
    * Constructs a new VpInfosApi. 
    * @alias module:api/VpInfosApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the vpInfosControllerAddLabel operation.
     * @callback moduleapi/VpInfosApi~vpInfosControllerAddLabelCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VpInfoResponseDto{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * VP情報へのラベル追加
     * リクエストパラメータのidで指定された単一のVP情報に対して、任意の管理用ラベルを追加します。
     * @param {module:model/AddLabelToVpInfoDto} body 
     * @param {String} id 
     * @param {module:api/VpInfosApi~vpInfosControllerAddLabelCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    vpInfosControllerAddLabel(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling vpInfosControllerAddLabel");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling vpInfosControllerAddLabel");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = VpInfoResponseDto;

      return this.apiClient.callApi(
        '/api/v1/vp-infos/{id}/label', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the vpInfosControllerConnectUser operation.
     * @callback moduleapi/VpInfosApi~vpInfosControllerConnectUserCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * VP情報へのクライアントアカウント紐付け
     * VP情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
     * @param {module:model/UpdateVcInfoDto} body 
     * @param {String} id 
     * @param {module:api/VpInfosApi~vpInfosControllerConnectUserCallback} callback The callback function, accepting three arguments: error, data, response
     */
    vpInfosControllerConnectUser(body, id, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling vpInfosControllerConnectUser");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling vpInfosControllerConnectUser");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v1/vp-infos/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the vpInfosControllerCreate operation.
     * @callback moduleapi/VpInfosApi~vpInfosControllerCreateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 新規VP生成
     * 新規VPを生成します。
     * @param {module:model/CreateVpInfoDto} body 
     * @param {module:api/VpInfosApi~vpInfosControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    vpInfosControllerCreate(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling vpInfosControllerCreate");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearer'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v1/vp-infos', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the vpInfosControllerDisconnectUser operation.
     * @callback moduleapi/VpInfosApi~vpInfosControllerDisconnectUserCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * VP情報のクライアントアカウント紐付け解除
     * VP情報に紐付いたクライアントアカウントの紐付けを解除します。
     * @param {String} id 
     * @param {module:api/VpInfosApi~vpInfosControllerDisconnectUserCallback} callback The callback function, accepting three arguments: error, data, response
     */
    vpInfosControllerDisconnectUser(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling vpInfosControllerDisconnectUser");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/v1/vp-infos/{id}/user', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the vpInfosControllerFindAll operation.
     * @callback moduleapi/VpInfosApi~vpInfosControllerFindAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VpInfoResponseDto{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * VP情報一覧取得
     * アプリケーションが管理するVP情報を一覧として値を返します。
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
     * @param {Number} opts.limit (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
     * @param {String} opts.label (任意) 例: \&quot;vc-for-project1\&quot;
     * @param {String} opts.description (任意) 
     * @param {module:api/VpInfosApi~vpInfosControllerFindAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    vpInfosControllerFindAll(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'page': opts['page'],'limit': opts['limit'],'label': opts['label'],'description': opts['description']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = VpInfoResponseDto;

      return this.apiClient.callApi(
        '/api/v1/vp-infos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the vpInfosControllerFindOne operation.
     * @callback moduleapi/VpInfosApi~vpInfosControllerFindOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VpInfoDetailDto{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * VP情報詳細取得
     * リクエストパラメータのidで指定された単一のVP情報の詳細情報の値を返します。
     * @param {String} id 
     * @param {module:api/VpInfosApi~vpInfosControllerFindOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    vpInfosControllerFindOne(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling vpInfosControllerFindOne");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = VpInfoDetailDto;

      return this.apiClient.callApi(
        '/api/v1/vp-infos/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the vpInfosControllerUpload operation.
     * @callback moduleapi/VpInfosApi~vpInfosControllerUploadCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VpInfoResponseDto{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 新規VPアップロード
     * 外部で発行された既存VPをアップロードし、本アプリケーションに保存します。。
     * @param {Object} credentialObject 
     * @param {String} label 
     * @param {String} description 
     * @param {module:api/VpInfosApi~vpInfosControllerUploadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    vpInfosControllerUpload(credentialObject, label, description, callback) {
      
      let postBody = null;
      // verify the required parameter 'credentialObject' is set
      if (credentialObject === undefined || credentialObject === null) {
        throw new Error("Missing the required parameter 'credentialObject' when calling vpInfosControllerUpload");
      }
      // verify the required parameter 'label' is set
      if (label === undefined || label === null) {
        throw new Error("Missing the required parameter 'label' when calling vpInfosControllerUpload");
      }
      // verify the required parameter 'description' is set
      if (description === undefined || description === null) {
        throw new Error("Missing the required parameter 'description' when calling vpInfosControllerUpload");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'credentialObject': credentialObject,'label': label,'description': description
      };

      let authNames = ['bearer'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = VpInfoResponseDto;

      return this.apiClient.callApi(
        '/api/v1/vp-infos/upload', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}