/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IDroitDashboardAdminApi);
  }
}(this, function(expect, IDroitDashboardAdminApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateVcSchemaDto', function() {
      beforeEach(function() {
        instance = new IDroitDashboardAdminApi.CreateVcSchemaDto();
      });

      it('should create an instance of CreateVcSchemaDto', function() {
        // TODO: update the code to test CreateVcSchemaDto
        expect(instance).to.be.a(IDroitDashboardAdminApi.CreateVcSchemaDto);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property version (base name: "version")', function() {
        // TODO: update the code to test the property version
        expect(instance).to.have.property('version');
        // expect(instance.version).to.be(expectedValueLiteral);
      });

      it('should have the property contexts (base name: "contexts")', function() {
        // TODO: update the code to test the property contexts
        expect(instance).to.have.property('contexts');
        // expect(instance.contexts).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property isBadgeSchema (base name: "isBadgeSchema")', function() {
        // TODO: update the code to test the property isBadgeSchema
        expect(instance).to.have.property('isBadgeSchema');
        // expect(instance.isBadgeSchema).to.be(expectedValueLiteral);
      });

      it('should have the property fileId (base name: "fileId")', function() {
        // TODO: update the code to test the property fileId
        expect(instance).to.have.property('fileId');
        // expect(instance.fileId).to.be(expectedValueLiteral);
      });

      it('should have the property propArray (base name: "propArray")', function() {
        // TODO: update the code to test the property propArray
        expect(instance).to.have.property('propArray');
        // expect(instance.propArray).to.be(expectedValueLiteral);
      });

    });
  });

}));
