/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import AddLabelToBadgeDto from './model/AddLabelToBadgeDto';
import AddLabelToDidInfoDto from './model/AddLabelToDidInfoDto';
import AddLabelToVcInfoDto from './model/AddLabelToVcInfoDto';
import AddLabelToVpInfoDto from './model/AddLabelToVpInfoDto';
import AllOfBadgeResponseDtoVcInfo from './model/AllOfBadgeResponseDtoVcInfo';
import AllOfBadgeResponseDtoVcSchema from './model/AllOfBadgeResponseDtoVcSchema';
import AllOfBadgeVcInfo from './model/AllOfBadgeVcInfo';
import AllOfBadgeVcSchema from './model/AllOfBadgeVcSchema';
import AllOfDidInfoCreatedBy from './model/AllOfDidInfoCreatedBy';
import AllOfDidInfoResponseDtoDidInfo from './model/AllOfDidInfoResponseDtoDidInfo';
import AllOfDidInfoUser from './model/AllOfDidInfoUser';
import AllOfDidInfoVpInfos from './model/AllOfDidInfoVpInfos';
import AllOfFileCreatedBy from './model/AllOfFileCreatedBy';
import AllOfFileResponseDtoCreatedBy from './model/AllOfFileResponseDtoCreatedBy';
import AllOfFileVcSchema from './model/AllOfFileVcSchema';
import AllOfGroupCreatedBy from './model/AllOfGroupCreatedBy';
import AllOfGroupResponseDtoCreatedBy from './model/AllOfGroupResponseDtoCreatedBy';
import AllOfUserCreatedBy from './model/AllOfUserCreatedBy';
import AllOfUserResponseDtoCreatedBy from './model/AllOfUserResponseDtoCreatedBy';
import AllOfVcContextVcSchema from './model/AllOfVcContextVcSchema';
import AllOfVcInfoBadge from './model/AllOfVcInfoBadge';
import AllOfVcInfoCreatedBy from './model/AllOfVcInfoCreatedBy';
import AllOfVcInfoResponseDtoVcInfo from './model/AllOfVcInfoResponseDtoVcInfo';
import AllOfVcInfoUser from './model/AllOfVcInfoUser';
import AllOfVcInfoVcSchema from './model/AllOfVcInfoVcSchema';
import AllOfVcSchemaCreatedBy from './model/AllOfVcSchemaCreatedBy';
import AllOfVcSchemaFile from './model/AllOfVcSchemaFile';
import AllOfVcSchemaPropertyVcSchema from './model/AllOfVcSchemaPropertyVcSchema';
import AllOfVcSchemaResponseDtoCreatedBy from './model/AllOfVcSchemaResponseDtoCreatedBy';
import AllOfVcSchemaResponseDtoFile from './model/AllOfVcSchemaResponseDtoFile';
import AllOfVerificationCreatedBy from './model/AllOfVerificationCreatedBy';
import AllOfVerificationResponseDtoCreatedBy from './model/AllOfVerificationResponseDtoCreatedBy';
import AllOfVerificationResponseDtoVcInfo from './model/AllOfVerificationResponseDtoVcInfo';
import AllOfVerificationResponseDtoVpInfo from './model/AllOfVerificationResponseDtoVpInfo';
import AllOfVerificationVcInfo from './model/AllOfVerificationVcInfo';
import AllOfVerificationVpInfo from './model/AllOfVerificationVpInfo';
import AllOfVerificationsResponseDtoLinks from './model/AllOfVerificationsResponseDtoLinks';
import AllOfVerificationsResponseDtoMeta from './model/AllOfVerificationsResponseDtoMeta';
import AllOfVpInfoCreatedBy from './model/AllOfVpInfoCreatedBy';
import AllOfVpInfoDetailDtoVpInfo from './model/AllOfVpInfoDetailDtoVpInfo';
import AllOfVpInfoDidInfo from './model/AllOfVpInfoDidInfo';
import AllOfVpInfoUser from './model/AllOfVpInfoUser';
import Badge from './model/Badge';
import BadgeResponseDto from './model/BadgeResponseDto';
import BadgesFileBody from './model/BadgesFileBody';
import BadgesResponseDto from './model/BadgesResponseDto';
import ConnectDidInfosDto from './model/ConnectDidInfosDto';
import ConnectUsersDto from './model/ConnectUsersDto';
import ConnectVcInfosDto from './model/ConnectVcInfosDto';
import ConnectVcSchemasDto from './model/ConnectVcSchemasDto';
import ConnectVpInfosDto from './model/ConnectVpInfosDto';
import CreateBadgeDto from './model/CreateBadgeDto';
import CreateDidDto from './model/CreateDidDto';
import CreateGroupDto from './model/CreateGroupDto';
import CreateUserDto from './model/CreateUserDto';
import CreateVcInfoDto from './model/CreateVcInfoDto';
import CreateVcSchemaDto from './model/CreateVcSchemaDto';
import CreateVpInfoDto from './model/CreateVpInfoDto';
import DidInfo from './model/DidInfo';
import DidInfoResponseDto from './model/DidInfoResponseDto';
import DidInfosResponseDto from './model/DidInfosResponseDto';
import File from './model/File';
import FileResponseDto from './model/FileResponseDto';
import FilesResponseDto from './model/FilesResponseDto';
import GenerateDidDto from './model/GenerateDidDto';
import GenerateVpDto from './model/GenerateVpDto';
import GetProfileResponseDto from './model/GetProfileResponseDto';
import Group from './model/Group';
import GroupResponseDto from './model/GroupResponseDto';
import GroupsResponseDto from './model/GroupsResponseDto';
import IssueVcInfoDto from './model/IssueVcInfoDto';
import LinkDto from './model/LinkDto';
import Mail from './model/Mail';
import MailsResponseDto from './model/MailsResponseDto';
import MetaDto from './model/MetaDto';
import RegisterDidDto from './model/RegisterDidDto';
import RegistrationProcessDto from './model/RegistrationProcessDto';
import ResolveDidDto from './model/ResolveDidDto';
import ResolveDidResponseDto from './model/ResolveDidResponseDto';
import SendMailBatchDto from './model/SendMailBatchDto';
import SendMailDto from './model/SendMailDto';
import Setting from './model/Setting';
import SettingListResponseDto from './model/SettingListResponseDto';
import SettingResponseDto from './model/SettingResponseDto';
import SignInDto from './model/SignInDto';
import SignInResponseDto from './model/SignInResponseDto';
import UpdateVcInfoDto from './model/UpdateVcInfoDto';
import UpdateVcSchemaDto from './model/UpdateVcSchemaDto';
import UploadVCDto from './model/UploadVCDto';
import UploadVPDto from './model/UploadVPDto';
import User from './model/User';
import UserResponseDto from './model/UserResponseDto';
import UserToken from './model/UserToken';
import UsersResponseDto from './model/UsersResponseDto';
import V1FilesBody from './model/V1FilesBody';
import VcContext from './model/VcContext';
import VcInfo from './model/VcInfo';
import VcInfoResponseDto from './model/VcInfoResponseDto';
import VcInfosResponseDto from './model/VcInfosResponseDto';
import VcSchema from './model/VcSchema';
import VcSchemaProperty from './model/VcSchemaProperty';
import VcSchemaResponseDto from './model/VcSchemaResponseDto';
import VcSchemasResponseDto from './model/VcSchemasResponseDto';
import Verification from './model/Verification';
import VerificationDto from './model/VerificationDto';
import VerificationResponseDto from './model/VerificationResponseDto';
import VerificationsResponseDto from './model/VerificationsResponseDto';
import VerifiyBadgeFileReponseDto from './model/VerifiyBadgeFileReponseDto';
import VerifiyBadgeReponseDto from './model/VerifiyBadgeReponseDto';
import VerifyBadgeDto from './model/VerifyBadgeDto';
import VpInfo from './model/VpInfo';
import VpInfoDetailDto from './model/VpInfoDetailDto';
import VpInfoResponseDto from './model/VpInfoResponseDto';
import AuthApi from './api/AuthApi';
import BadgesApi from './api/BadgesApi';
import DidInfosApi from './api/DidInfosApi';
import FilesApi from './api/FilesApi';
import GroupsApi from './api/GroupsApi';
import HealthApi from './api/HealthApi';
import MailsApi from './api/MailsApi';
import SettingsApi from './api/SettingsApi';
import UsersApi from './api/UsersApi';
import VcInfosApi from './api/VcInfosApi';
import VcSchemasApi from './api/VcSchemasApi';
import VerificationsApi from './api/VerificationsApi';
import VpInfosApi from './api/VpInfosApi';

/**
* ______httpswww_fore_co_ltdjaDecentralizd_Identifiers__Verifiable_Credentials_DIDVC_REST_API_______DID_________________VC_______________idroit_dashboard_admin_UI_httpsadmin_idroit_dashboard_com_______idroit_dashboard________idroit_dashboard____________Universal_Resolver_httpsdev_uniresolver_io_______W3C_DID_Core_1_0_httpswww_w3_orgTRdid_core_______Verifiable_Credentials_Data_Model_v2_0_httpswww_w3_orgTRvc_data_model_2_0__.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var IDroitDashboardAdminApi = require('index'); // See note below*.
* var xxxSvc = new IDroitDashboardAdminApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new IDroitDashboardAdminApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new IDroitDashboardAdminApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new IDroitDashboardAdminApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.9.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddLabelToBadgeDto model constructor.
     * @property {module:model/AddLabelToBadgeDto}
     */
    AddLabelToBadgeDto,

    /**
     * The AddLabelToDidInfoDto model constructor.
     * @property {module:model/AddLabelToDidInfoDto}
     */
    AddLabelToDidInfoDto,

    /**
     * The AddLabelToVcInfoDto model constructor.
     * @property {module:model/AddLabelToVcInfoDto}
     */
    AddLabelToVcInfoDto,

    /**
     * The AddLabelToVpInfoDto model constructor.
     * @property {module:model/AddLabelToVpInfoDto}
     */
    AddLabelToVpInfoDto,

    /**
     * The AllOfBadgeResponseDtoVcInfo model constructor.
     * @property {module:model/AllOfBadgeResponseDtoVcInfo}
     */
    AllOfBadgeResponseDtoVcInfo,

    /**
     * The AllOfBadgeResponseDtoVcSchema model constructor.
     * @property {module:model/AllOfBadgeResponseDtoVcSchema}
     */
    AllOfBadgeResponseDtoVcSchema,

    /**
     * The AllOfBadgeVcInfo model constructor.
     * @property {module:model/AllOfBadgeVcInfo}
     */
    AllOfBadgeVcInfo,

    /**
     * The AllOfBadgeVcSchema model constructor.
     * @property {module:model/AllOfBadgeVcSchema}
     */
    AllOfBadgeVcSchema,

    /**
     * The AllOfDidInfoCreatedBy model constructor.
     * @property {module:model/AllOfDidInfoCreatedBy}
     */
    AllOfDidInfoCreatedBy,

    /**
     * The AllOfDidInfoResponseDtoDidInfo model constructor.
     * @property {module:model/AllOfDidInfoResponseDtoDidInfo}
     */
    AllOfDidInfoResponseDtoDidInfo,

    /**
     * The AllOfDidInfoUser model constructor.
     * @property {module:model/AllOfDidInfoUser}
     */
    AllOfDidInfoUser,

    /**
     * The AllOfDidInfoVpInfos model constructor.
     * @property {module:model/AllOfDidInfoVpInfos}
     */
    AllOfDidInfoVpInfos,

    /**
     * The AllOfFileCreatedBy model constructor.
     * @property {module:model/AllOfFileCreatedBy}
     */
    AllOfFileCreatedBy,

    /**
     * The AllOfFileResponseDtoCreatedBy model constructor.
     * @property {module:model/AllOfFileResponseDtoCreatedBy}
     */
    AllOfFileResponseDtoCreatedBy,

    /**
     * The AllOfFileVcSchema model constructor.
     * @property {module:model/AllOfFileVcSchema}
     */
    AllOfFileVcSchema,

    /**
     * The AllOfGroupCreatedBy model constructor.
     * @property {module:model/AllOfGroupCreatedBy}
     */
    AllOfGroupCreatedBy,

    /**
     * The AllOfGroupResponseDtoCreatedBy model constructor.
     * @property {module:model/AllOfGroupResponseDtoCreatedBy}
     */
    AllOfGroupResponseDtoCreatedBy,

    /**
     * The AllOfUserCreatedBy model constructor.
     * @property {module:model/AllOfUserCreatedBy}
     */
    AllOfUserCreatedBy,

    /**
     * The AllOfUserResponseDtoCreatedBy model constructor.
     * @property {module:model/AllOfUserResponseDtoCreatedBy}
     */
    AllOfUserResponseDtoCreatedBy,

    /**
     * The AllOfVcContextVcSchema model constructor.
     * @property {module:model/AllOfVcContextVcSchema}
     */
    AllOfVcContextVcSchema,

    /**
     * The AllOfVcInfoBadge model constructor.
     * @property {module:model/AllOfVcInfoBadge}
     */
    AllOfVcInfoBadge,

    /**
     * The AllOfVcInfoCreatedBy model constructor.
     * @property {module:model/AllOfVcInfoCreatedBy}
     */
    AllOfVcInfoCreatedBy,

    /**
     * The AllOfVcInfoResponseDtoVcInfo model constructor.
     * @property {module:model/AllOfVcInfoResponseDtoVcInfo}
     */
    AllOfVcInfoResponseDtoVcInfo,

    /**
     * The AllOfVcInfoUser model constructor.
     * @property {module:model/AllOfVcInfoUser}
     */
    AllOfVcInfoUser,

    /**
     * The AllOfVcInfoVcSchema model constructor.
     * @property {module:model/AllOfVcInfoVcSchema}
     */
    AllOfVcInfoVcSchema,

    /**
     * The AllOfVcSchemaCreatedBy model constructor.
     * @property {module:model/AllOfVcSchemaCreatedBy}
     */
    AllOfVcSchemaCreatedBy,

    /**
     * The AllOfVcSchemaFile model constructor.
     * @property {module:model/AllOfVcSchemaFile}
     */
    AllOfVcSchemaFile,

    /**
     * The AllOfVcSchemaPropertyVcSchema model constructor.
     * @property {module:model/AllOfVcSchemaPropertyVcSchema}
     */
    AllOfVcSchemaPropertyVcSchema,

    /**
     * The AllOfVcSchemaResponseDtoCreatedBy model constructor.
     * @property {module:model/AllOfVcSchemaResponseDtoCreatedBy}
     */
    AllOfVcSchemaResponseDtoCreatedBy,

    /**
     * The AllOfVcSchemaResponseDtoFile model constructor.
     * @property {module:model/AllOfVcSchemaResponseDtoFile}
     */
    AllOfVcSchemaResponseDtoFile,

    /**
     * The AllOfVerificationCreatedBy model constructor.
     * @property {module:model/AllOfVerificationCreatedBy}
     */
    AllOfVerificationCreatedBy,

    /**
     * The AllOfVerificationResponseDtoCreatedBy model constructor.
     * @property {module:model/AllOfVerificationResponseDtoCreatedBy}
     */
    AllOfVerificationResponseDtoCreatedBy,

    /**
     * The AllOfVerificationResponseDtoVcInfo model constructor.
     * @property {module:model/AllOfVerificationResponseDtoVcInfo}
     */
    AllOfVerificationResponseDtoVcInfo,

    /**
     * The AllOfVerificationResponseDtoVpInfo model constructor.
     * @property {module:model/AllOfVerificationResponseDtoVpInfo}
     */
    AllOfVerificationResponseDtoVpInfo,

    /**
     * The AllOfVerificationVcInfo model constructor.
     * @property {module:model/AllOfVerificationVcInfo}
     */
    AllOfVerificationVcInfo,

    /**
     * The AllOfVerificationVpInfo model constructor.
     * @property {module:model/AllOfVerificationVpInfo}
     */
    AllOfVerificationVpInfo,

    /**
     * The AllOfVerificationsResponseDtoLinks model constructor.
     * @property {module:model/AllOfVerificationsResponseDtoLinks}
     */
    AllOfVerificationsResponseDtoLinks,

    /**
     * The AllOfVerificationsResponseDtoMeta model constructor.
     * @property {module:model/AllOfVerificationsResponseDtoMeta}
     */
    AllOfVerificationsResponseDtoMeta,

    /**
     * The AllOfVpInfoCreatedBy model constructor.
     * @property {module:model/AllOfVpInfoCreatedBy}
     */
    AllOfVpInfoCreatedBy,

    /**
     * The AllOfVpInfoDetailDtoVpInfo model constructor.
     * @property {module:model/AllOfVpInfoDetailDtoVpInfo}
     */
    AllOfVpInfoDetailDtoVpInfo,

    /**
     * The AllOfVpInfoDidInfo model constructor.
     * @property {module:model/AllOfVpInfoDidInfo}
     */
    AllOfVpInfoDidInfo,

    /**
     * The AllOfVpInfoUser model constructor.
     * @property {module:model/AllOfVpInfoUser}
     */
    AllOfVpInfoUser,

    /**
     * The Badge model constructor.
     * @property {module:model/Badge}
     */
    Badge,

    /**
     * The BadgeResponseDto model constructor.
     * @property {module:model/BadgeResponseDto}
     */
    BadgeResponseDto,

    /**
     * The BadgesFileBody model constructor.
     * @property {module:model/BadgesFileBody}
     */
    BadgesFileBody,

    /**
     * The BadgesResponseDto model constructor.
     * @property {module:model/BadgesResponseDto}
     */
    BadgesResponseDto,

    /**
     * The ConnectDidInfosDto model constructor.
     * @property {module:model/ConnectDidInfosDto}
     */
    ConnectDidInfosDto,

    /**
     * The ConnectUsersDto model constructor.
     * @property {module:model/ConnectUsersDto}
     */
    ConnectUsersDto,

    /**
     * The ConnectVcInfosDto model constructor.
     * @property {module:model/ConnectVcInfosDto}
     */
    ConnectVcInfosDto,

    /**
     * The ConnectVcSchemasDto model constructor.
     * @property {module:model/ConnectVcSchemasDto}
     */
    ConnectVcSchemasDto,

    /**
     * The ConnectVpInfosDto model constructor.
     * @property {module:model/ConnectVpInfosDto}
     */
    ConnectVpInfosDto,

    /**
     * The CreateBadgeDto model constructor.
     * @property {module:model/CreateBadgeDto}
     */
    CreateBadgeDto,

    /**
     * The CreateDidDto model constructor.
     * @property {module:model/CreateDidDto}
     */
    CreateDidDto,

    /**
     * The CreateGroupDto model constructor.
     * @property {module:model/CreateGroupDto}
     */
    CreateGroupDto,

    /**
     * The CreateUserDto model constructor.
     * @property {module:model/CreateUserDto}
     */
    CreateUserDto,

    /**
     * The CreateVcInfoDto model constructor.
     * @property {module:model/CreateVcInfoDto}
     */
    CreateVcInfoDto,

    /**
     * The CreateVcSchemaDto model constructor.
     * @property {module:model/CreateVcSchemaDto}
     */
    CreateVcSchemaDto,

    /**
     * The CreateVpInfoDto model constructor.
     * @property {module:model/CreateVpInfoDto}
     */
    CreateVpInfoDto,

    /**
     * The DidInfo model constructor.
     * @property {module:model/DidInfo}
     */
    DidInfo,

    /**
     * The DidInfoResponseDto model constructor.
     * @property {module:model/DidInfoResponseDto}
     */
    DidInfoResponseDto,

    /**
     * The DidInfosResponseDto model constructor.
     * @property {module:model/DidInfosResponseDto}
     */
    DidInfosResponseDto,

    /**
     * The File model constructor.
     * @property {module:model/File}
     */
    File,

    /**
     * The FileResponseDto model constructor.
     * @property {module:model/FileResponseDto}
     */
    FileResponseDto,

    /**
     * The FilesResponseDto model constructor.
     * @property {module:model/FilesResponseDto}
     */
    FilesResponseDto,

    /**
     * The GenerateDidDto model constructor.
     * @property {module:model/GenerateDidDto}
     */
    GenerateDidDto,

    /**
     * The GenerateVpDto model constructor.
     * @property {module:model/GenerateVpDto}
     */
    GenerateVpDto,

    /**
     * The GetProfileResponseDto model constructor.
     * @property {module:model/GetProfileResponseDto}
     */
    GetProfileResponseDto,

    /**
     * The Group model constructor.
     * @property {module:model/Group}
     */
    Group,

    /**
     * The GroupResponseDto model constructor.
     * @property {module:model/GroupResponseDto}
     */
    GroupResponseDto,

    /**
     * The GroupsResponseDto model constructor.
     * @property {module:model/GroupsResponseDto}
     */
    GroupsResponseDto,

    /**
     * The IssueVcInfoDto model constructor.
     * @property {module:model/IssueVcInfoDto}
     */
    IssueVcInfoDto,

    /**
     * The LinkDto model constructor.
     * @property {module:model/LinkDto}
     */
    LinkDto,

    /**
     * The Mail model constructor.
     * @property {module:model/Mail}
     */
    Mail,

    /**
     * The MailsResponseDto model constructor.
     * @property {module:model/MailsResponseDto}
     */
    MailsResponseDto,

    /**
     * The MetaDto model constructor.
     * @property {module:model/MetaDto}
     */
    MetaDto,

    /**
     * The RegisterDidDto model constructor.
     * @property {module:model/RegisterDidDto}
     */
    RegisterDidDto,

    /**
     * The RegistrationProcessDto model constructor.
     * @property {module:model/RegistrationProcessDto}
     */
    RegistrationProcessDto,

    /**
     * The ResolveDidDto model constructor.
     * @property {module:model/ResolveDidDto}
     */
    ResolveDidDto,

    /**
     * The ResolveDidResponseDto model constructor.
     * @property {module:model/ResolveDidResponseDto}
     */
    ResolveDidResponseDto,

    /**
     * The SendMailBatchDto model constructor.
     * @property {module:model/SendMailBatchDto}
     */
    SendMailBatchDto,

    /**
     * The SendMailDto model constructor.
     * @property {module:model/SendMailDto}
     */
    SendMailDto,

    /**
     * The Setting model constructor.
     * @property {module:model/Setting}
     */
    Setting,

    /**
     * The SettingListResponseDto model constructor.
     * @property {module:model/SettingListResponseDto}
     */
    SettingListResponseDto,

    /**
     * The SettingResponseDto model constructor.
     * @property {module:model/SettingResponseDto}
     */
    SettingResponseDto,

    /**
     * The SignInDto model constructor.
     * @property {module:model/SignInDto}
     */
    SignInDto,

    /**
     * The SignInResponseDto model constructor.
     * @property {module:model/SignInResponseDto}
     */
    SignInResponseDto,

    /**
     * The UpdateVcInfoDto model constructor.
     * @property {module:model/UpdateVcInfoDto}
     */
    UpdateVcInfoDto,

    /**
     * The UpdateVcSchemaDto model constructor.
     * @property {module:model/UpdateVcSchemaDto}
     */
    UpdateVcSchemaDto,

    /**
     * The UploadVCDto model constructor.
     * @property {module:model/UploadVCDto}
     */
    UploadVCDto,

    /**
     * The UploadVPDto model constructor.
     * @property {module:model/UploadVPDto}
     */
    UploadVPDto,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserResponseDto model constructor.
     * @property {module:model/UserResponseDto}
     */
    UserResponseDto,

    /**
     * The UserToken model constructor.
     * @property {module:model/UserToken}
     */
    UserToken,

    /**
     * The UsersResponseDto model constructor.
     * @property {module:model/UsersResponseDto}
     */
    UsersResponseDto,

    /**
     * The V1FilesBody model constructor.
     * @property {module:model/V1FilesBody}
     */
    V1FilesBody,

    /**
     * The VcContext model constructor.
     * @property {module:model/VcContext}
     */
    VcContext,

    /**
     * The VcInfo model constructor.
     * @property {module:model/VcInfo}
     */
    VcInfo,

    /**
     * The VcInfoResponseDto model constructor.
     * @property {module:model/VcInfoResponseDto}
     */
    VcInfoResponseDto,

    /**
     * The VcInfosResponseDto model constructor.
     * @property {module:model/VcInfosResponseDto}
     */
    VcInfosResponseDto,

    /**
     * The VcSchema model constructor.
     * @property {module:model/VcSchema}
     */
    VcSchema,

    /**
     * The VcSchemaProperty model constructor.
     * @property {module:model/VcSchemaProperty}
     */
    VcSchemaProperty,

    /**
     * The VcSchemaResponseDto model constructor.
     * @property {module:model/VcSchemaResponseDto}
     */
    VcSchemaResponseDto,

    /**
     * The VcSchemasResponseDto model constructor.
     * @property {module:model/VcSchemasResponseDto}
     */
    VcSchemasResponseDto,

    /**
     * The Verification model constructor.
     * @property {module:model/Verification}
     */
    Verification,

    /**
     * The VerificationDto model constructor.
     * @property {module:model/VerificationDto}
     */
    VerificationDto,

    /**
     * The VerificationResponseDto model constructor.
     * @property {module:model/VerificationResponseDto}
     */
    VerificationResponseDto,

    /**
     * The VerificationsResponseDto model constructor.
     * @property {module:model/VerificationsResponseDto}
     */
    VerificationsResponseDto,

    /**
     * The VerifiyBadgeFileReponseDto model constructor.
     * @property {module:model/VerifiyBadgeFileReponseDto}
     */
    VerifiyBadgeFileReponseDto,

    /**
     * The VerifiyBadgeReponseDto model constructor.
     * @property {module:model/VerifiyBadgeReponseDto}
     */
    VerifiyBadgeReponseDto,

    /**
     * The VerifyBadgeDto model constructor.
     * @property {module:model/VerifyBadgeDto}
     */
    VerifyBadgeDto,

    /**
     * The VpInfo model constructor.
     * @property {module:model/VpInfo}
     */
    VpInfo,

    /**
     * The VpInfoDetailDto model constructor.
     * @property {module:model/VpInfoDetailDto}
     */
    VpInfoDetailDto,

    /**
     * The VpInfoResponseDto model constructor.
     * @property {module:model/VpInfoResponseDto}
     */
    VpInfoResponseDto,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The BadgesApi service constructor.
    * @property {module:api/BadgesApi}
    */
    BadgesApi,

    /**
    * The DidInfosApi service constructor.
    * @property {module:api/DidInfosApi}
    */
    DidInfosApi,

    /**
    * The FilesApi service constructor.
    * @property {module:api/FilesApi}
    */
    FilesApi,

    /**
    * The GroupsApi service constructor.
    * @property {module:api/GroupsApi}
    */
    GroupsApi,

    /**
    * The HealthApi service constructor.
    * @property {module:api/HealthApi}
    */
    HealthApi,

    /**
    * The MailsApi service constructor.
    * @property {module:api/MailsApi}
    */
    MailsApi,

    /**
    * The SettingsApi service constructor.
    * @property {module:api/SettingsApi}
    */
    SettingsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi,

    /**
    * The VcInfosApi service constructor.
    * @property {module:api/VcInfosApi}
    */
    VcInfosApi,

    /**
    * The VcSchemasApi service constructor.
    * @property {module:api/VcSchemasApi}
    */
    VcSchemasApi,

    /**
    * The VerificationsApi service constructor.
    * @property {module:api/VerificationsApi}
    */
    VerificationsApi,

    /**
    * The VpInfosApi service constructor.
    * @property {module:api/VpInfosApi}
    */
    VpInfosApi
};
