/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IDroitDashboardAdminApi);
  }
}(this, function(expect, IDroitDashboardAdminApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IDroitDashboardAdminApi.DidInfosApi();
  });

  describe('(package)', function() {
    describe('DidInfosApi', function() {
      describe('didInfosControllerAddLabel', function() {
        it('should call didInfosControllerAddLabel successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerAddLabel call and complete the assertions
          /*

          instance.didInfosControllerAddLabel(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.DidInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('didInfosControllerConnectUser', function() {
        it('should call didInfosControllerConnectUser successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerConnectUser call and complete the assertions
          /*

          instance.didInfosControllerConnectUser(id, userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.DidInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('didInfosControllerCreate', function() {
        it('should call didInfosControllerCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerCreate call
          /*

          instance.didInfosControllerCreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('didInfosControllerDisconnectUser', function() {
        it('should call didInfosControllerDisconnectUser successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerDisconnectUser call
          /*

          instance.didInfosControllerDisconnectUser(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('didInfosControllerFindAll', function() {
        it('should call didInfosControllerFindAll successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerFindAll call and complete the assertions
          /*
          var opts = {};

          instance.didInfosControllerFindAll(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.DidInfosResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('didInfosControllerFindOne', function() {
        it('should call didInfosControllerFindOne successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerFindOne call and complete the assertions
          /*

          instance.didInfosControllerFindOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.DidInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('didInfosControllerRegister', function() {
        it('should call didInfosControllerRegister successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerRegister call
          /*

          instance.didInfosControllerRegister(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('didInfosControllerRemove', function() {
        it('should call didInfosControllerRemove successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerRemove call
          /*

          instance.didInfosControllerRemove(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('didInfosControllerResolve', function() {
        it('should call didInfosControllerResolve successfully', function(done) {
          // TODO: uncomment, update parameter values for didInfosControllerResolve call and complete the assertions
          /*

          instance.didInfosControllerResolve(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.ResolveDidResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
