/*
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IDroitDashboardAdminApi);
  }
}(this, function(expect, IDroitDashboardAdminApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IDroitDashboardAdminApi.VcInfosApi();
  });

  describe('(package)', function() {
    describe('VcInfosApi', function() {
      describe('vcInfosControllerAddLabel', function() {
        it('should call vcInfosControllerAddLabel successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerAddLabel call and complete the assertions
          /*

          instance.vcInfosControllerAddLabel(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.VcInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('vcInfosControllerConnectUser', function() {
        it('should call vcInfosControllerConnectUser successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerConnectUser call
          /*

          instance.vcInfosControllerConnectUser(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('vcInfosControllerCreate', function() {
        it('should call vcInfosControllerCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerCreate call and complete the assertions
          /*

          instance.vcInfosControllerCreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.VcInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('vcInfosControllerDisconnectUser', function() {
        it('should call vcInfosControllerDisconnectUser successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerDisconnectUser call
          /*

          instance.vcInfosControllerDisconnectUser(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('vcInfosControllerFindAll', function() {
        it('should call vcInfosControllerFindAll successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerFindAll call and complete the assertions
          /*
          var opts = {};

          instance.vcInfosControllerFindAll(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.VcInfosResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('vcInfosControllerFindOne', function() {
        it('should call vcInfosControllerFindOne successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerFindOne call and complete the assertions
          /*

          instance.vcInfosControllerFindOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.VcInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('vcInfosControllerGenerateVp', function() {
        it('should call vcInfosControllerGenerateVp successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerGenerateVp call and complete the assertions
          /*

          instance.vcInfosControllerGenerateVp(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.VcInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('vcInfosControllerIssue', function() {
        it('should call vcInfosControllerIssue successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerIssue call and complete the assertions
          /*

          instance.vcInfosControllerIssue(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.VcInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('vcInfosControllerUpload', function() {
        it('should call vcInfosControllerUpload successfully', function(done) {
          // TODO: uncomment, update parameter values for vcInfosControllerUpload call and complete the assertions
          /*

          instance.vcInfosControllerUpload(credentialObject, label, description, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(IDroitDashboardAdminApi.VcInfoResponseDto);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
